import Nav from "@/components/Nav";
import Providers from "@/lib/Providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {

  return (
    <html lang="en">
      <body className="h-screen bg-slate-100">
        <Providers>
          <Nav />
          <>{children}</>
        </Providers>
      </body>
    </html>
  );
}
