import Icons from "@/components/Icons";
import "./globals.css";
import {Inter} from "next/font/google";
import { Home } from "lucide-react";
import Nav from "@/components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="h-screen bg-slate-100">
        <Nav />
        <>{children}</>
      </body>
    </html>
  );
}


